CREATE TABLE `reconciliation_receivables_info` (
  `pk_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `batch_id` varchar(100) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '同步批次',
  `original_id` int(11) DEFAULT NULL COMMENT '原Oracle_id',
  `period_name` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '账期=当前月份-1',
  `balance_date` date DEFAULT NULL COMMENT '时点余额生成日期',
  `receivable_type` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '应收类型',
  `receivable_id` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '应收编号',
  `bg` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'BG',
  `department` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '部门',
  `overdue_type_warning_email_category` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '逾期类型-预警邮件分类用（2）后续更名',
  `overdue_type_warning_attachment_category` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '逾期类型-预警附件分类用（3）后续更名',
  `receivable_management_action` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '应收管理动作',
  `customer_name` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '客户名称',
  `business_type` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '业务类型',
  `settlement_group` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '结算组',
  `coa` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'COA',
  `kpi` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'KPI',
  `service_provision_date` date DEFAULT NULL COMMENT '服务提供日（GL日期）',
  `settlement_occurrence_date` date DEFAULT NULL COMMENT '结算发生日',
  `currency` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '币种',
  `receivable_balance` decimal(20,2) DEFAULT NULL COMMENT '应收余额',
  `receivable_balance_cny` decimal(20,2) DEFAULT NULL COMMENT '应收余额CNY',
  `receivable_amount` decimal(20,2) DEFAULT NULL COMMENT '应收金额',
  `ou_id` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `ou_name` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `data_range` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '数据范围 0-境内 1 -境外',
  `period_caliber` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '账期计算口径',
  `contract_id` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '合同号',
  `channel` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '渠道',
  `invoice_number` varchar(4000) COLLATE utf8mb4_bin DEFAULT NULL,
  `invoice_date` date DEFAULT NULL COMMENT '开票日期',
  `latest_transcription_date` date DEFAULT NULL COMMENT '最晚转录日',
  `payment_period` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '回款账期',
  `latest_payment_due_date` date DEFAULT NULL COMMENT '最晚应回款日',
  `payment_overdue_days` int(11) DEFAULT NULL COMMENT '回款逾期（单位：天）',
  `invoice_period` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '开票账期',
  `latest_invoice_due_date` date DEFAULT NULL COMMENT '最晚应开票日',
  `delayed_invoice_days` int(11) DEFAULT NULL COMMENT '延迟开票（单位：天）',
  `reconciliation_period` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '对账账期',
  `latest_reconciliation_due_date` date DEFAULT NULL COMMENT '最晚应对账日',
  `delayed_reconciliation_days` int(11) DEFAULT NULL COMMENT '延迟对账（单位：天）',
  `overdue_time_period` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '逾期时间段',
  `overdue_reason` text COLLATE utf8mb4_bin COMMENT '逾期原因/回款计划/止损措施',
  `revenue_reporting_id` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '收入上报编号',
  `business_liaison` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '业务对接人',
  `business_leader` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '业务leader',
  `business_director` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '业务总监',
  `business_gm` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '业务GM',
  `financial_liaison` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '财管对接人',
  `financial_leader` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '财管leader',
  `financial_director` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '财管总监',
  `financial_gm` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '财管GM',
  `receivable_management_center_liaison` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '应收管理中心对接人',
  `receivable_management_center_leader` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '应收管理中心leader',
  `receivable_management_center_director` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '应收管理中心总监',
  `receivable_management_center_gm` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '应收管理中心GM',
  `generate_email_separately` varchar(50) COLLATE utf8mb4_bin DEFAULT '否' COMMENT '是否单独生成邮件',
  `merge_warning_recipients` varchar(50) COLLATE utf8mb4_bin DEFAULT '是' COMMENT '预警收件人是否合并',
  `latest_association` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '最新关联关系',
  `is_overdue` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '是否逾期',
  `is_recon` varchar(50) COLLATE utf8mb4_bin DEFAULT '是' COMMENT '是否参与对账',
  `is_business_gm_foreign` varchar(50) COLLATE utf8mb4_bin DEFAULT '否' COMMENT '业务GM是否外籍',
  `send_email` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '发送邮箱',
  `external_send_additions` text COLLATE utf8mb4_bin COMMENT '对外发送新增',
  `customer_email` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '客户邮箱',
  `remark` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '备注',
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_date` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `payment_period_1` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL,
  `invoice_period_1` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL,
  `reconciliation_period_1` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL,
  `biz_customer_id` varchar(500) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '业务客户ID',
  `is_merge_business` varchar(20) COLLATE utf8mb4_bin DEFAULT '是' COMMENT '业务对接人是否合并',
  `ID` int(11) DEFAULT NULL,
  `due_info_detail` varchar(50) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '逾期情况：已逾期、未逾期、某月即将逾期',
  PRIMARY KEY (`pk_id`),
  UNIQUE KEY `idx_receivable_id_billing_date` (`receivable_id`,`period_name`),
  KEY `idx_bg` (`bg`),
  KEY `idx_business_liaison_prefix` (`business_liaison`(10)),
  KEY `idx_period_name` (`period_name`),
  FULLTEXT KEY `idx_business_liaison` (`business_liaison`),
  FULLTEXT KEY `idx_business_gm` (`business_gm`)
) ENGINE=InnoDB AUTO_INCREMENT=7352802 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

